version: '3.9'

services:
  java_app:
    container_name: java_app
    image: online_store_app:1.0.0
    build: .
    ports:
      - 8080:8080
    depends_on:
      - java_db
    volumes:
      - online_store_volume:/home/app_data
    environment:
      DATABASE_USERNAME: postgres
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: java_db
    volumes:
      - online_store_volume:/home/db_data
  frontend:
    container_name: Frontend
    build: ../StoreFrontend/OnlineStoreFE
    ports:
      - "5173:5173"
    depends_on:
      - java_app
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080
  sonarqube:
    container_name: Sonarqube
    image: sonarqube:latest
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/java_db
      SONARQUBE_JDBC_USERNAME: postgres
      SONARQUBE_JDBC_PASSWORD: postgres
    ports:
      - "9000:9000"
    depends_on:
      - java_db

volumes:
  online_store_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: src/main/resources
