--Users
INSERT INTO APP_USERS (NAME, SUBNAME, EMAIL, PASSWORD, LOGIN_COUNT) VALUES
('ARTHUR', 'MORGAN', 'EMAIL1@GMAIL.COM', '1234', 2)
ON CONFLICT (email)
DO NOTHING;

INSERT INTO APP_USERS (NAME, SUBNAME, EMAIL, PASSWORD, LOGIN_COUNT) VALUES
('Lerois', 'Jenkis', 'EMAIL2@GMAIL.COM', '1234', 1)
ON CONFLICT (email)
DO NOTHING;

--Roles
INSERT INTO ROLES (NAME) VALUES
('ADMIN')
ON CONFLICT (NAME)
DO NOTHING;

INSERT INTO ROLES (NAME) VALUES
('USER')
ON CONFLICT (NAME)
DO NOTHING;

--User_Roles
INSERT INTO USER_ROLES (user_id, role_id) VALUES
(1,1)
ON CONFLICT
DO NOTHING;

INSERT INTO USER_ROLES (user_id, role_id) VALUES
(2,1)
ON CONFLICT
DO NOTHING;

--Categories
INSERT INTO CATEGORIES (ID, NAME) VALUES
(0, 'Undefined')
ON CONFLICT (name)
DO NOTHING;

INSERT INTO CATEGORIES (NAME) VALUES
('Category1')
ON CONFLICT (name)
DO NOTHING;

INSERT INTO CATEGORIES (NAME) VALUES
('Category2')
ON CONFLICT (name)
DO NOTHING;

INSERT INTO CATEGORIES (NAME) VALUES
('Category3')
ON CONFLICT (name)
DO NOTHING;

--Products
INSERT INTO PRODUCTS (TITLE, PRICE, BRAND, COLOR, WEIGHT, VOLUME, STOCK, CATEGORY_ID) VALUES
('Product1', 10, 'Adidas', 'Black',184, '732x179x494 mm', 10, 1)
ON CONFLICT (TITLE)
DO NOTHING;

INSERT INTO PRODUCTS (TITLE, PRICE, BRAND, COLOR, WEIGHT, VOLUME, STOCK, CATEGORY_ID) VALUES
('Product2', 1, 'Nike', 'White',184, '732x179x494 mm', 10, 1)
ON CONFLICT (TITLE)
DO NOTHING;

INSERT INTO PRODUCTS (TITLE, PRICE, BRAND, COLOR, WEIGHT, VOLUME, STOCK, CATEGORY_ID) VALUES
('Product3', 1, 'Nike', 'White',184, '732x179x494 mm', 10, 2)
ON CONFLICT (TITLE)
DO NOTHING;

INSERT INTO PRODUCTS (TITLE, PRICE, BRAND, COLOR, WEIGHT, VOLUME, STOCK, CATEGORY_ID) VALUES
('Product4', 1, 'Nike', 'White',184, '732x179x494 mm', 10, 3)
ON CONFLICT (TITLE)
DO NOTHING;

-- Delivery Methods
INSERT INTO DELIVERY_METHODS (d_method)
VALUES ('Standar shopping')
ON CONFLICT (D_METHOD)
DO NOTHING;

INSERT INTO DELIVERY_METHODS (d_method)
VALUES ('Express shopping')
ON CONFLICT (D_METHOD)
DO NOTHING;

INSERT INTO DELIVERY_METHODS (d_method)
VALUES ('In-Store Pickup')
ON CONFLICT (D_METHOD)
DO NOTHING;

--PaymentMethod
INSERT INTO PAYMENT_METHODS (p_method)
VALUES ('Cash')
ON CONFLICT (P_METHOD)
DO NOTHING;

INSERT INTO PAYMENT_METHODS (p_method)
VALUES ('By card')
ON CONFLICT (P_METHOD)
DO NOTHING;